### PR TITLE
Adding sudo and new user

### PR DESCRIPTION
**Pull request by thegillion**
Added sudo where needed 
Added new user note
Added install command for openjdk

### CODE REVIEW

**Comment by AndrewX192** [comment]
You shouldn't need to run gradle as root - what's happening that prompted you to add that?

Perhaps you need to chown that back to your non-root user?

**Comment by thegillion** [comment]
> Got permission denied while trying to connect to the Docker daemon socket 
User cannot connect to Docker.

**Comment by AndrewX192** [comment]
Ah, you should add your less privileged user to the docker group then (logout and back in), rather than running gradle as root.

**Comment by AndrewX192** [comment]
@thegillion are you still working on this or should it be closed?

**Comment by AndrewX192** [comment]
I'm closing this since sufficient time has passed that the instructions have changed (and mostly deferred to arcus-k8)

**Pull request closed without merging**
